# Generated by Django 5.1.5 on 2025-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("policy_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[("auto", "Auto"), ("home", "Home")], max_length=50
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
