# Generated by Django 5.1.5 on 2025-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="customer_name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_type",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("home", "Home"),
                    ("life", "Life"),
                    ("travel", "Travel"),
                ],
                max_length=64,
            ),
        ),
    ]
