# Generated by Django 5.1.5 on 2025-02-05 21:59

from django.db import migrations
from datetime import date, timedelta
from policies.models import PolicyType


def populate_initial_policies(apps, schema_editor):
    Policy = apps.get_model("policies", "Policy")

    Policy.objects.create(
        customer_name="Eric Mariot",
        policy_type=PolicyType.TRAVEL,
        expiry_date=date.today() + timedelta(days=365),
    )
    Policy.objects.create(
        customer_name="Rafa",
        policy_type=PolicyType.HOME,
        expiry_date=date.today() + timedelta(days=355),
    )
    Policy.objects.create(
        customer_name="Renato",
        policy_type=PolicyType.LIFE,
        expiry_date=date.today() + timedelta(days=345),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_initial_policies)]
